version: 0.2

env:
  variables:
    NODE_ENV: "${env}"
    DISTRIBUTION_ID: "${distributionid}"

phases:
  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id ${distributionid} --paths "/*"


cache:
  paths:
    - /root/.npm/**/*