version: 0.2

env:
  variables:
    NODE_ENV: "${env}"
    S3_STATIC_WEBSITE_BUCKET: "${staticwebsite}"
    DISTRIBUTION_ID: "${distributionid}"

phases:
  install:
    runtime-versions:
      nodejs: 16.x
    commands:
      - cd application
      - npm install

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - aws s3 sync "dist" "s3://${staticwebsite}" --delete


cache:
  paths:
    - /root/.npm/**/*